# Main Public Trainee Portal
http://sih2026.avishkark.in, https://sih2026.avishkark.in {
    reverse_proxy localhost:3000
}

# Supabase API & Auth Gateway
http://api.avishkark.in, https://api.avishkark.in {
    reverse_proxy localhost:8000
}

# Supabase Studio Dashboard
http://studio.avishkark.in, https://studio.avishkark.in {
    reverse_proxy localhost:8000 {
        header_up Host {host}
        header_up X-Forwarded-Proto https
    }
}

# Admin Panel
http://administrator.avishkark.in, https://administrator.avishkark.in {
    reverse_proxy localhost:3001
}
