-- =====================================================================
-- Migration: Real Accredited Course Catalog Expansion
-- Schema aligned: sector, skill_tags, enrolled_count, estimated_hours
-- =====================================================================

CREATE UNIQUE INDEX IF NOT EXISTS idx_external_courses_title ON public.external_courses (title);

INSERT INTO public.external_courses (
  title, 
  provider, 
  platform, 
  sector, 
  duration_weeks, 
  estimated_hours,
  rating, 
  enrolled_count, 
  is_free, 
  has_certificate,
  url, 
  skill_tags, 
  nsqf_level
) VALUES
  -- 1. Apparel & Fashion
  (
    'Apparel Manufacturing & Garment Technology',
    'IIT Delhi / NPTEL',
    'NPTEL',
    'Apparel & Fashion',
    12,
    60,
    4.9,
    14820,
    true,
    true,
    'https://onlinecourses.nptel.ac.in/noc24_te01/preview',
    ARRAY['Fabric Defect Identification', 'AQL 2.5 Quality Inspection', 'Garment CAD Grading', 'Industrial Stitching'],
    5
  ),
  (
    'Garment Manufacturing Technology & Quality Control',
    'NIFT / Swayam (Govt of India)',
    'Swayam',
    'Apparel & Fashion',
    8,
    40,
    4.8,
    9240,
    true,
    true,
    'https://swayam.gov.in/explorer?category=Design',
    ARRAY['Pattern Making', 'Industrial Stitching', 'Quality Compliance', 'Packaging Protocols'],
    4
  ),
  (
    'Fashion Design & Garment Construction Masterclass',
    'Institut Français de la Mode (IFM)',
    'Coursera',
    'Apparel & Fashion',
    6,
    30,
    4.7,
    31200,
    false,
    true,
    'https://www.coursera.org/learn/fashion-design',
    ARRAY['Pattern Making', 'Garment CAD Grading', 'Boutique Collection Design'],
    5
  ),
  (
    'Apparel Made-ups & Home Furnishing Quality Lead',
    'Apparel SSC (AMHSSC)',
    'Skill India',
    'Apparel & Fashion',
    10,
    50,
    4.8,
    18450,
    true,
    true,
    'https://www.skillindiadigital.gov.in/courses',
    ARRAY['AQL 2.5 Quality Inspection', 'Fabric Defect Identification', 'Shop Floor Supervision'],
    5
  ),

  -- 2. Renewable Energy & Solar PV
  (
    'Design of Photovoltaic Systems & Grid Integration',
    'IISc Bangalore & IIT Roorkee / NPTEL',
    'NPTEL',
    'Renewable Energy',
    12,
    60,
    4.9,
    18320,
    true,
    true,
    'https://onlinecourses.nptel.ac.in/noc24_ee22/preview',
    ARRAY['Solar PV Installation', 'Inverter Wiring', 'Grid Net Metering Integration', 'Megger Insulation Testing'],
    6
  ),
  (
    'Solar Photovoltaic Energy Systems: Design & Installation',
    'IIT Roorkee / Swayam',
    'Swayam',
    'Renewable Energy',
    8,
    40,
    4.8,
    14200,
    true,
    true,
    'https://swayam.gov.in/explorer?category=Engineering_and_Technology',
    ARRAY['Solar PV Installation', 'Inverter Wiring', 'Earthing & Lightning Protection', 'OSHA Safety Protocols'],
    4
  ),
  (
    'Renewable Energy Technology & Smart Grids Specialization',
    'University of Colorado Boulder',
    'Coursera',
    'Renewable Energy',
    16,
    80,
    4.9,
    27500,
    false,
    true,
    'https://www.coursera.org/specializations/renewable-energy-technology',
    ARRAY['Solar PV Installation', 'Grid Net Metering Integration', 'Battery Management Systems (BMS)'],
    6
  ),
  (
    'Surya Mitra Solar PV Technician Certification',
    'NISE / NSDC',
    'Skill India',
    'Renewable Energy',
    12,
    60,
    4.9,
    42800,
    true,
    true,
    'https://www.skillindiadigital.gov.in/courses/surya-mitra',
    ARRAY['Solar PV Installation', 'Inverter Wiring', 'Earthing & Lightning Protection', 'Megger Insulation Testing'],
    4
  ),

  -- 3. Automotive & EV Technology
  (
    'Electric Vehicles: Part 1 - Powertrain & Battery Management',
    'IIT Madras / NPTEL',
    'NPTEL',
    'Automotive & EV',
    12,
    60,
    4.9,
    22400,
    true,
    true,
    'https://onlinecourses.nptel.ac.in/noc24_ee45/preview',
    ARRAY['EV Diagnostics & CAN-Bus', 'Lithium Battery Management (BMS)', 'High-Voltage Traction Motor Service'],
    6
  ),
  (
    'Automotive Electrical & Electronic Systems',
    'NITTTR Chandigarh / Swayam',
    'Swayam',
    'Automotive & EV',
    8,
    40,
    4.7,
    11600,
    true,
    true,
    'https://swayam.gov.in/explorer?category=Mechanical_Engineering',
    ARRAY['Automotive Wiring Diagnostics', 'ECU & OBD-II Scanning', 'High-Voltage Safety Protocols'],
    5
  ),
  (
    'Electric Vehicle Technology & Battery Management Systems',
    'University of Michigan',
    'Coursera',
    'Automotive & EV',
    10,
    50,
    4.8,
    19800,
    false,
    true,
    'https://www.coursera.org/learn/electric-vehicle-technology',
    ARRAY['Lithium Battery Management (BMS)', 'EV Diagnostics & CAN-Bus', 'Fast Charging Infrastructure'],
    6
  ),
  (
    'EV Service Lead & Battery Diagnostic Technician',
    'Automotive Skills Development Council (ASDC)',
    'Skill India',
    'Automotive & EV',
    14,
    70,
    4.8,
    28900,
    true,
    true,
    'https://www.skillindiadigital.gov.in/courses',
    ARRAY['EV Diagnostics & CAN-Bus', 'Lithium Battery Management (BMS)', 'High-Voltage Safety Protocols'],
    5
  ),

  -- 4. Precision CNC Machining & Manufacturing
  (
    'Machining Sciences and Precision CNC Technology',
    'IIT Kanpur / NPTEL',
    'NPTEL',
    'Automotive & EV',
    12,
    60,
    4.9,
    13900,
    true,
    true,
    'https://onlinecourses.nptel.ac.in/noc24_me15/preview',
    ARRAY['G-Code Programming', 'CNC Milling & Turning', 'Vernier & Micrometer Metrology', 'Geometric Dimensioning & Tolerancing (GD&T)'],
    5
  ),
  (
    'CAD/CAM Toolpath Simulation & CNC Machine Operations',
    'Autodesk / Coursera',
    'Coursera',
    'Automotive & EV',
    6,
    30,
    4.8,
    16400,
    false,
    true,
    'https://www.coursera.org/learn/autodesk-fusion-360-cam-toolpaths',
    ARRAY['CAD/CAM Toolpath Simulation', 'G-Code Programming', 'CNC Milling & Turning'],
    5
  ),
  (
    'CNC Lathe & Milling Machine Operator (Level 4)',
    'Capital Goods Skill Council (CGSC)',
    'Skill India',
    'Automotive & EV',
    12,
    60,
    4.7,
    21500,
    true,
    true,
    'https://www.skillindiadigital.gov.in/courses',
    ARRAY['CNC Milling & Turning', 'Vernier & Micrometer Metrology', 'Geometric Dimensioning & Tolerancing (GD&T)'],
    4
  ),

  -- 5. IT, Cloud & Full-Stack Engineering
  (
    'Programming, Data Structures & Cloud Architecture',
    'IIT Madras / NPTEL',
    'NPTEL',
    'IT & Digital',
    12,
    60,
    4.9,
    45600,
    true,
    true,
    'https://onlinecourses.nptel.ac.in/noc24_cs01/preview',
    ARRAY['Full-Stack Web Architecture', 'Next.js & TypeScript', 'PostgreSQL & Schema Optimization', 'Git & CI/CD Deployment'],
    6
  ),
  (
    'Meta Front-End Developer Professional Certificate',
    'Meta Staff Engineers',
    'Coursera',
    'IT & Digital',
    24,
    120,
    4.8,
    94000,
    false,
    true,
    'https://www.coursera.org/professional-certificates/meta-front-end-developer',
    ARRAY['Next.js & TypeScript', 'Full-Stack Web Architecture', 'Git & CI/CD Deployment'],
    6
  ),
  (
    'Google IT Automation with Python Professional Certificate',
    'Google',
    'Coursera',
    'IT & Digital',
    18,
    90,
    4.8,
    88300,
    false,
    true,
    'https://www.coursera.org/professional-certificates/google-it-automation',
    ARRAY['Git & CI/CD Deployment', 'Cloud Architecture', 'Automated Testing'],
    6
  ),
  (
    'Cloud Computing Applications & Distributed Systems',
    'IIT Kharagpur / Swayam',
    'Swayam',
    'IT & Digital',
    8,
    40,
    4.8,
    24100,
    true,
    true,
    'https://swayam.gov.in/explorer?category=Computer_Science_and_Engineering',
    ARRAY['Cloud Architecture', 'PostgreSQL & Schema Optimization', 'Git & CI/CD Deployment'],
    6
  ),

  -- 6. MSME Entrepreneurship, Retail & Healthcare
  (
    'Micro-Enterprise Accounting, GST & Udyam Compliance',
    'MSSDS & MSInS',
    'MSSDS',
    'Retail & Commerce',
    6,
    30,
    4.8,
    15700,
    true,
    true,
    'https://www.mssds.gov.in',
    ARRAY['GST & Udyam MSME Compliance', 'Inventory & Working Capital Management', 'PMEGP & Mudra Subsidy Application', 'Digital Payments & Point of Sale (POS)'],
    4
  ),
  (
    'Entrepreneurship, Feasibility & MSME Business Incubation',
    'CEC / Swayam (Govt of India)',
    'Swayam',
    'Retail & Commerce',
    8,
    40,
    4.7,
    18900,
    true,
    true,
    'https://swayam.gov.in/explorer?category=Management',
    ARRAY['GST & Udyam MSME Compliance', 'Inventory & Working Capital Management', 'Customer Relationship Management'],
    5
  ),
  (
    'Supply Chain Operations & MSME Logistics Specialization',
    'Rutgers University',
    'Coursera',
    'Retail & Commerce',
    12,
    60,
    4.8,
    21300,
    false,
    true,
    'https://www.coursera.org/specializations/supply-chain-operations',
    ARRAY['Inventory & Working Capital Management', 'Customer Relationship Management'],
    5
  ),
  (
    'General Duty Assistant (Healthcare & Patient Care Lead)',
    'Healthcare SSC (HSSC)',
    'Skill India',
    'Healthcare & Caregiving',
    12,
    60,
    4.9,
    34200,
    true,
    true,
    'https://www.skillindiadigital.gov.in/courses',
    ARRAY['Patient Vitals Monitoring', 'CPR & BLS Emergency Response', 'Sterilization & Aseptic Technique', 'Biomedical Waste Protocols', 'Electronic Health Records (EHR)'],
    4
  ),
  (
    'Hospital Operations Management & Biomedical Safety',
    'IIT Roorkee / NPTEL',
    'NPTEL',
    'Healthcare & Caregiving',
    8,
    40,
    4.8,
    12800,
    true,
    true,
    'https://onlinecourses.nptel.ac.in/noc24_mg31/preview',
    ARRAY['Biomedical Waste Protocols', 'Sterilization & Aseptic Technique', 'Electronic Health Records (EHR)'],
    5
  )
ON CONFLICT (title) DO UPDATE SET
  provider = EXCLUDED.provider,
  platform = EXCLUDED.platform,
  sector = EXCLUDED.sector,
  duration_weeks = EXCLUDED.duration_weeks,
  estimated_hours = EXCLUDED.estimated_hours,
  rating = EXCLUDED.rating,
  enrolled_count = EXCLUDED.enrolled_count,
  is_free = EXCLUDED.is_free,
  has_certificate = EXCLUDED.has_certificate,
  url = EXCLUDED.url,
  skill_tags = EXCLUDED.skill_tags,
  nsqf_level = EXCLUDED.nsqf_level;
